export const city = [
   { label: "Abidjan"},
   { label: "Abu Dhabi"},
   { label: "Abuja"},
   { label: "Accra"},
   { label: "Addis Ababa"},
   { label: "Ahmedabad"},
   { label: "Aleppo"},
   { label: "Alexandria"},
   { label: "Algiers"},
   { label: "Almaty"},
   { label: "Amman"},
   { label: "Amsterdam"},
   { label: "Anchorage"},
   { label: "Andorra la Vella"},
   { label: "Ankara"},
   { label: "Antananarivo"},
   { label: "Apia"},
   { label: "Arnold"},
   { label: "Ashgabat"},
   { label: "Asmara"},
   { label: "Asuncion"},
   { label: "Athens"},
   { label: "Auckland"},
   { label: "Avarua"},
   { label: "Baghdad"},
   { label: "Baku"},
   { label: "Bamako"},
   { label: "Banda Aceh"},
   { label: "Bandar Seri Begawan"},
   { label: "Bandung"},
   { label: "Bangkok"},
   { label: "Bangui"},
   { label: "Banjul"},
   { label: "Barcelona"},
   { label: "Barranquilla"},
   { label: "Basrah"},
   { label: "Basse-Terre"},
   { label: "Basseterre"},
   { label: "Beijing"},
   { label: "Beirut"},
   { label: "Bekasi"},
   { label: "Belem"},
   { label: "Belgrade"},
   { label: "Belmopan"},
   { label: "Belo Horizonte"},
   { label: "Bengaluru"},
   { label: "Berlin"},
   { label: "Bern"},
   { label: "Bishkek"},
   { label: "Bissau"},
   { label: "Bogota"},
   { label: "Brasilia"},
   { label: "Bratislava"},
   { label: "Brazzaville"},
   { label: "Bridgetown"},
   { label: "Brisbane"},
   { label: "Brussels"},
   { label: "Bucharest"},
   { label: "Budapest"},
   { label: "Buenos Aires"},
   { label: "Bujumbura"},
   { label: "Bursa"},
   { label: "Busan"},
   { label: "Cairo"},
   { label: "Cali"},
   { label: "Caloocan"},
   { label: "Camayenne"},
   { label: "Canberra"},
   { label: "Cape Town"},
   { label: "Caracas"},
   { label: "Casablanca"},
   { label: "Castries"},
   { label: "Cayenne"},
   { label: "Charlotte Amalie"},
   { label: "Chengdu"},
   { label: "Chennai"},
   { label: "Chicago"},
   { label: "Chisinau"},
   { label: "Chittagong"},
   { label: "Chongqing"},
   { label: "Colombo"},
   { label: "Conakry"},
   { label: "Copenhagen"},
   { label: "Cordoba"},
   { label: "Curitiba"},
   { label: "Daegu"},
   { label: "Daejeon"},
   { label: "Dakar"},
   { label: "Dallas"},
   { label: "Damascus"},
   { label: "Dar es Salaam"},
   { label: "Delhi"},
   { label: "Denver"},
   { label: "Dhaka"},
   { label: "Dili"},
   { label: "Djibouti"},
   { label: "Dodoma"},
   { label: "Doha"},
   { label: "Dongguan"},
   { label: "Douala"},
   { label: "Douglas"},
   { label: "Dubai"},
   { label: "Dublin"},
   { label: "Durban"},
   { label: "Dushanbe"},
   { label: "Faisalabad"},
   { label: "Fort-de-France"},
   { label: "Fortaleza"},
   { label: "Freetown"},
   { label: "Fukuoka"},
   { label: "Funafuti"},
   { label: "Gaborone"},
   { label: "George Town"},
   { label: "Georgetown"},
   { label: "Gibraltar"},
   { label: "Gitega"},
   { label: "Giza"},
   { label: "Guadalajara"},
   { label: "Guangzhou"},
   { label: "Guatemala City"},
   { label: "Guayaquil"},
   { label: "Gujranwala"},
   { label: "Gustavia"},
   { label: "Gwangju"},
   { label: "Hamburg"},
   { label: "Hanoi"},
   { label: "Harare"},
   { label: "Havana"},
   { label: "Helsinki"},
   { label: "Ho Chi Minh City"},
   { label: "Hong Kong"},
   { label: "Honiara"},
   { label: "Honolulu"},
   { label: "Houston"},
   { label: "Hyderabad"},
   { label: "Hyderabad"},
   { label: "Ibadan"},
   { label: "Incheon"},
   { label: "Isfahan"},
   { label: "Islamabad"},
   { label: "Istanbul"},
   { label: "Izmir"},
   { label: "Jaipur"},
   { label: "Jakarta"},
   { label: "Jeddah"},
   { label: "Jerusalem"},
   { label: "Johannesburg"},
   { label: "Juarez"},
   { label: "Juba"},
   { label: "Kabul"},
   { label: "Kaduna"},
   { label: "Kampala"},
   { label: "Kano"},
   { label: "Kanpur"},
   { label: "Kaohsiung"},
   { label: "Karachi"},
   { label: "Karaj"},
   { label: "Kathmandu"},
   { label: "Kawasaki"},
   { label: "Kharkiv"},
   { label: "Khartoum"},
   { label: "Khulna"},
   { label: "Kigali"},
   { label: "Kingsburg"},
   { label: "Kingston"},
   { label: "Kingstown"},
   { label: "Kinshasa"},
   { label: "Kobe"},
   { label: "Kolkata"},
   { label: "Kota Bharu"},
   { label: "Kowloon"},
   { label: "Kuala Lumpur"},
   { label: "Kumasi"},
   { label: "Kuwait"},
   { label: "Kyiv"},
   { label: "Kyoto"},
   { label: "La Paz"},
   { label: "Lagos"},
   { label: "Lahore"},
   { label: "Libreville"},
   { label: "Lilongwe"},
   { label: "Lima"},
   { label: "Lisbon"},
   { label: "Ljubljana"},
   { label: "Lome"},
   { label: "London"},
   { label: "Los Angeles"},
   { label: "Luanda"},
   { label: "Lubumbashi"},
   { label: "Lusaka"},
   { label: "Luxembourg"},
   { label: "Macau"},
   { label: "Madrid"},
   { label: "Majuro"},
   { label: "Makassar"},
   { label: "Malabo"},
   { label: "Male"},
   { label: "Mamoudzou"},
   { label: "Managua"},
   { label: "Manama"},
   { label: "Manaus"},
   { label: "Manila"},
   { label: "Maputo"},
   { label: "Maracaibo"},
   { label: "Maracay"},
   { label: "Mariehamn"},
   { label: "Marigot"},
   { label: "Maseru"},
   { label: "Mashhad"},
   { label: "Mbabane"},
   { label: "Mecca"},
   { label: "Medan"},
   { label: "Medellin"},
   { label: "Medina"},
   { label: "Melbourne"},
   { label: "Mexico City"},
   { label: "Miami"},
   { label: "Minsk"},
   { label: "Mogadishu"},
   { label: "Monaco"},
   { label: "Monrovia"},
   { label: "Montevideo"},
   { label: "Montreal"},
   { label: "Moroni"},
   { label: "Moscow"},
   { label: "Mosul"},
   { label: "Multan"},
   { label: "Mumbai"},
   { label: "Muscat"},
   { label: "N'Djamena"},
   { label: "Nagoya"},
   { label: "Nairobi"},
   { label: "Nanchong"},
   { label: "Nanjing"},
   { label: "Nassau"},
   { label: "Nay Pyi Taw"},
   { label: "New York"},
   { label: "Niamey"},
   { label: "Nicosia"},
   { label: "Nouakchott"},
   { label: "Noumea"},
   { label: "Novosibirsk"},
   { label: "Nuku'alofa"},
   { label: "Nur-Sultan"},
   { label: "Nuuk"},
   { label: "Oranjestad"},
   { label: "Osaka"},
   { label: "Oslo"},
   { label: "Ottawa"},
   { label: "Ouagadougou"},
   { label: "Pago Pago"},
   { label: "Palembang"},
   { label: "Palo Alto"},
   { label: "Panama"},
   { label: "Papeete"},
   { label: "Paramaribo"},
   { label: "Paris"},
   { label: "Perth"},
   { label: "Philadelphia"},
   { label: "Phnom Penh"},
   { label: "Phoenix"},
   { label: "Podgorica"},
   { label: "Port Louis"},
   { label: "Port Moresby"},
   { label: "Port of Spain"},
   { label: "Port-Vila"},
   { label: "Port-au-Prince"},
   { label: "Porto Alegre"},
   { label: "Porto-Novo"},
   { label: "Prague"},
   { label: "Praia"},
   { label: "Pretoria"},
   { label: "Pristina"},
   { label: "Puebla"},
   { label: "Pune"},
   { label: "Pyongyang"},
   { label: "Quezon City"},
   { label: "Quito"},
   { label: "Rabat"},
   { label: "Rawalpindi"},
   { label: "Recife"},
   { label: "Reykjavik"},
   { label: "Riga"},
   { label: "Rio de Janeiro"},
   { label: "Riyadh"},
   { label: "Road Town"},
   { label: "Rome"},
   { label: "Roseau"},
   { label: "Saint George's"},
   { label: "Saint Helier"},
   { label: "Saint John's"},
   { label: "Saint Peter Port"},
   { label: "Saint Petersburg"},
   { label: "Saint-Denis"},
   { label: "Saint-Pierre"},
   { label: "Saipan"},
   { label: "Salvador"},
   { label: "San Antonio"},
   { label: "San Diego"},
   { label: "San Francisco"},
   { label: "San Jose"},
   { label: "San Juan"},
   { label: "San Marino"},
   { label: "San Salvador"},
   { label: "Sanaa"},
   { label: "Santa Cruz de la Sierra"},
   { label: "Santiago"},
   { label: "Santo Domingo"},
   { label: "Sao Paulo"},
   { label: "Sao Tome"},
   { label: "Sapporo"},
   { label: "Sarajevo"},
   { label: "Seattle"},
   { label: "Semarang"},
   { label: "Seoul"},
   { label: "Shanghai"},
   { label: "Sharjah"},
   { label: "Shenzhen"},
   { label: "Singapore"},
   { label: "Skopje"},
   { label: "Sofia"},
   { label: "South Tangerang"},
   { label: "Soweto"},
   { label: "Stockholm"},
   { label: "Sucre"},
   { label: "Surabaya"},
   { label: "Surat"},
   { label: "Suva"},
   { label: "Sydney"},
   { label: "Tabriz"},
   { label: "Taipei"},
   { label: "Tallinn"},
   { label: "Tangerang"},
   { label: "Tarawa"},
   { label: "Tashkent"},
   { label: "Tbilisi"},
   { label: "Tegucigalpa"},
   { label: "Tehran"},
   { label: "Tel Aviv"},
   { label: "Thimphu"},
   { label: "Tianjin"},
   { label: "Tijuana"},
   { label: "Tirana"},
   { label: "Tokyo"},
   { label: "Toronto"},
   { label: "Torshavn"},
   { label: "Tripoli"},
   { label: "Tunis"},
   { label: "Ulan Bator"},
   { label: "Vaduz"},
   { label: "Valencia"},
   { label: "Valletta"},
   { label: "Vancouver"},
   { label: "Victoria"},
   { label: "Vienna"},
   { label: "Vientiane"},
   { label: "Vilnius"},
   { label: "Warsaw"},
   { label: "Washington"},
   { label: "Wellington"},
   { label: "Willemstad"},
   { label: "Windhoek"},
   { label: "Wuhan"},
   { label: "Xi'an"},
   { label: "Yamoussoukro"},
   { label: "Yaounde"},
   { label: "Yangon"},
   { label: "Yerevan"},
   { label: "Yekaterinburg"},
   { label: "Zagreb"},
   { label: "Yokohama"},
];