export const countryList = [
 {Title : "Afghanistan"},
 {Title : "Albania"},
 {Title : "Algeria"},
 {Title : "American Samoa"},
 {Title : "Andorra"},
 {Title : "Angola"},
 {Title : "Anguilla"},
 {Title : "Antarctica"},
 {Title : "Antigua and Barbuda"},
 {Title : "Argentina"},
 {Title : "Armenia"},
 {Title : "Aruba"},
 {Title : "Australia"},
 {Title : "Austria"},
 {Title : "Azerbaijan"},
 {Title : "Bahamas (the)"},
 {Title : "Bahrain"},
 {Title : "Bangladesh"},
 {Title : "Barbados"},
 {Title : "Belarus"},
 {Title : "Belgium"},
 {Title : "Belize"},
 {Title : "Benin"},
 {Title : "Bermuda"},
 {Title : "Bhutan"},
 {Title : "Bolivia (Plurinational State of)"},
 {Title : "Bonaire Sint Eustatius and Saba"},
 {Title : "Bosnia and Herzegovina"},
 {Title : "Botswana"},
 {Title : "Bouvet Island"},
 {Title : "Brazil"},
 {Title : "British Indian Ocean Territory (the)"},
 {Title : "Brunei Darussalam"},
 {Title : "Bulgaria"},
 {Title : "Burkina Faso"},
 {Title : "Burundi"},
 {Title : "Cabo Verde"},
 {Title : "Cambodia"},
 {Title : "Cameroon"},
 {Title : "Canada"},
 {Title : "Cayman Islands (the)"},
 {Title : "Central African Republic (the)"},
 {Title : "Chad"},
 {Title : "Chile"},
 {Title : "China"},
 {Title : "Christmas Island"},
 {Title : "Cocos (Keeling) Islands (the)"},
 {Title : "Colombia"},
 {Title : "Comoros (the)"},
 {Title : "Congo (the Democratic Republic of the)"},
 {Title : "Congo (the)"},
 {Title : "Cook Islands (the)"},
 {Title : "Costa Rica"},
 {Title : "Croatia"},
 {Title : "Cuba"},
 {Title : "Curaçao"},
 {Title : "Cyprus"},
 {Title : "Czechia"},
 {Title : "Côte d'Ivoire"},
 {Title : "Denmark"},
 {Title : "Djibouti"},
 {Title : "Dominica"},
 {Title : "Dominican Republic (the)"},
 {Title : "Ecuador"},
 {Title : "Egypt"},
 {Title : "El Salvador"},
 {Title : "Equatorial Guinea"},
 {Title : "Eritrea"},
 {Title : "Estonia"},
 {Title : "Eswatini"},
 {Title : "Ethiopia"},
 {Title : "Falkland Islands (the) [Malvinas]"},
 {Title : "Faroe Islands (the)"},
 {Title : "Fiji"},
 {Title : "Finland"},
 {Title : "France"},
 {Title : "French Guiana"},
 {Title : "French Polynesia"},
 {Title : "French Southern Territories (the)"},
 {Title : "Gabon"},
 {Title : "Gambia (the)"},
 {Title : "Georgia"},
 {Title : "Germany"},
 {Title : "Ghana"},
 {Title : "Gibraltar"},
 {Title : "Greece"},
 {Title : "Greenland"},
 {Title : "Grenada"},
 {Title : "Guadeloupe"},
 {Title : "Guam"},
 {Title : "Guatemala"},
 {Title : "Guernsey"},
 {Title : "Guinea"},
 {Title : "Guinea-Bissau"},
 {Title : "Guyana"},
 {Title : "Haiti"},
 {Title : "Heard Island and McDonald Islands"},
 {Title : "Holy See (the)"},
 {Title : "Honduras"},
 {Title : "Hong Kong"},
 {Title : "Hungary"},
 {Title : "Iceland"},
 {Title : "India"},
 {Title : "Indonesia"},
 {Title : "Iran (Islamic Republic of)"},
 {Title : "Iraq"},
 {Title : "Ireland"},
 {Title : "Isle of Man"},
 {Title : "Israel"},
 {Title : "Italy"},
 {Title : "Jamaica"},
 {Title : "Japan"},
 {Title : "Jersey"},
 {Title : "Jordan"},
 {Title : "Kazakhstan"},
 {Title : "Kenya"},
 {Title : "Kiribati"},
 {Title : "Korea (the Democratic People's Republic of)"},
 {Title : "Korea (the Republic of)"},
 {Title : "Kuwait"},
 {Title : "Kyrgyzstan"},
 {Title : "Lao People's Democratic Republic (the)"},
 {Title : "Latvia"},
 {Title : "Lebanon"},
 {Title : "Lesotho"},
 {Title : "Liberia"},
 {Title : "Libya"},
 {Title : "Liechtenstein"},
 {Title : "Lithuania"},
 {Title : "Luxembourg"},
 {Title : "Macao"},
 {Title : "Madagascar"},
 {Title : "Malawi"},
 {Title : "Malaysia"},
 {Title : "Maldives"},
 {Title : "Mali"},
 {Title : "Malta"},
 {Title : "Marshall Islands (the)"},
 {Title : "Martinique"},
 {Title : "Mauritania"},
 {Title : "Mauritius"},
 {Title : "Mayotte"},
 {Title : "Mexico"},
 {Title : "Micronesia (Federated States of)"},
 {Title : "Moldova (the Republic of)"},
 {Title : "Monaco"},
 {Title : "Mongolia"},
 {Title : "Montenegro"},
 {Title : "Montserrat"},
 {Title : "Morocco"},
 {Title : "Mozambique"},
 {Title : "Myanmar"},
 {Title : "Namibia"},
 {Title : "Nauru"},
 {Title : "Nepal"},
 {Title : "Netherlands (the)"},
 {Title : "New Caledonia"},
 {Title : "New Zealand"},
 {Title : "Nicaragua"},
 {Title : "Niger (the)"},
 {Title : "Nigeria"},
 {Title : "Niue"},
 {Title : "Norfolk Island"},
 {Title : "Northern Mariana Islands (the)"},
 {Title : "Norway"},
 {Title : "Oman"},
 {Title : "Pakistan"},
 {Title : "Palau"},
 {Title : "Palestine State of"},
 {Title : "Panama"},
 {Title : "Papua New Guinea"},
 {Title : "Paraguay"},
 {Title : "Peru"},
 {Title : "Philippines (the)"},
 {Title : "Pitcairn"},
 {Title : "Poland"},
 {Title : "Portugal"},
 {Title : "Puerto Rico"},
 {Title : "Qatar"},
 {Title : "Republic of North Macedonia"},
 {Title : "Romania"},
 {Title : "Russian Federation (the)"},
 {Title : "Rwanda"},
 {Title : "Réunion"},
 {Title : "Saint Barthélemy"},
 {Title : "Saint Helena Ascension and Tristan da Cunha"},
 {Title : "Saint Kitts and Nevis"},
 {Title : "Saint Lucia"},
 {Title : "Saint Martin (French part)"},
 {Title : "Saint Pierre and Miquelon"},
 {Title : "Saint Vincent and the Grenadines"},
 {Title : "Samoa"},
 {Title : "San Marino"},
 {Title : "Sao Tome and Principe"},
 {Title : "Saudi Arabia"},
 {Title : "Senegal"},
 {Title : "Serbia"},
 {Title : "Seychelles"},
 {Title : "Sierra Leone"},
 {Title : "Singapore"},
 {Title : "Sint Maarten (Dutch part)"},
 {Title : "Slovakia"},
 {Title : "Slovenia"},
 {Title : "Solomon Islands"},
 {Title : "Somalia"},
 {Title : "South Africa"},
 {Title : "South Georgia and the South Sandwich Islands"},
 {Title : "South Sudan"},
 {Title : "Spain"},
 {Title : "Sri Lanka"},
 {Title : "Sudan (the)"},
 {Title : "Suriname"},
 {Title : "Svalbard and Jan Mayen"},
 {Title : "Sweden"},
 {Title : "Switzerland"},
 {Title : "Syrian Arab Republic"},
 {Title : "Taiwan"},
 {Title : "Tajikistan"},
 {Title : "Tanzania United Republic of"},
 {Title : "Thailand"},
 {Title : "Timor-Leste"},
 {Title : "Togo"},
 {Title : "Tokelau"},
 {Title : "Tonga"},
 {Title : "Trinidad and Tobago"},
 {Title : "Tunisia"},
 {Title : "Turkey"},
 {Title : "Turkmenistan"},
 {Title : "Turks and Caicos Islands (the)"},
 {Title : "Tuvalu"},
 {Title : "Uganda"},
 {Title : "Ukraine"},
 {Title : "United Arab Emirates (the)"},
 {Title : "United Kingdom of Great Britain and Northern Ireland (the)"},
 {Title : "United States Minor Outlying Islands (the)"},
 {Title : "United States of America (the)"},
 {Title : "Uruguay"},
 {Title : "Uzbekistan"},
 {Title : "Vanuatu"},
 {Title : "Venezuela (Bolivarian Republic of)"},
 {Title : "Viet Nam"},
 {Title : "Virgin Islands (British)"},
 {Title : "Virgin Islands (U.S.)"},
 {Title : "Wallis and Futuna"},
 {Title : "Western Sahara"},
 {Title : "Yemen"},
 {Title : "Zambia"},
 {Title : "Zimbabwe"},
 {Title : "Åland Islands"},
];